# Generated by Codex on 2026-03-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
        ('users', '0002_user_nullable_email_phone'),
    ]

    operations = []
